version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - C:/Users/ADMIN/Desktop/mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: "mongodb://Admin:qwerty@mongo:27017"
  myapp:
    build: .
    container_name: myapp
    restart: always
    ports:
      - "5050:5050"
    environment:
      MONGO_URL: "mongodb://Admin:qwerty@mongo:27017"
   